local M = {}

M.MAX_STARTUP_ATTEMPTS = 5


M.TMRID_SELFTEST_FUNCTION=1
M.TMRID_MAIN_FUNCTION=2
M.TMRID_SLEEP_LOW_VOLTAGE=3


M.LOW_VOLTAGE_SLEEP_SEC = 30 * 60 -- 30min
M.BAT_LOW_VOLT_LIMIT = 3.4

M.SELFTEST_SCHEDULE_INTERVAL_MS = 3000
M.MAIN_SCHEDULE_INTERVAL_MS = 4000

return M