local M = {}

M.MAX_STARTUP_ATTEMPTS = 5


-- init.lua
M.TMRID_SELFTEST_FUNCTION=1
M.TMRID_MAIN_FUNCTION=2
M.TMRID_SLEEP_LOW_VOLTAGE=3
M.TMRID_PROGRAM_LOOP=4

-- led_helper.lua
M.TMRID_LED = 5
M.TMRID_CALLBACK = 6

--init.lua
M.LOW_VOLTAGE_SLEEP_SEC = 30 * 60 -- 30min
M.BAT_LOW_VOLT_LIMIT = 3.4
M.GACEFULLY_WAIT_BEFORE_SLEEP_MS = 5000

-- init.lua
M.SELFTEST_SCHEDULE_INTERVAL_MS = 3000
M.MAIN_SCHEDULE_INTERVAL_MS = 4000
M.PROGRAM_LOOP_SCHEDULE_INTERVAL_MS = (60 * 1000)


M.BLINK_CODE_ABORTING_EXEC = 3
M.MAX_ERROR_COUNT_BEFORE_RESTART = 3

return M
